service: aws-nodejs-template

provider:
  name: aws
  runtime: nodejs8.10

functions:
  index:
    handler: build/functions/handler.index

    events:
      - http:
          path: /index
          method: get

