service: aws-nodejs-template

provider:
  name: aws
  runtime: nodejs8.10

functions:
  index:
    handler: build/Handler.index

    events:
      - http:
          path: /index
          method: get

plugins:
  - serverless-offline

